# initialize-database
POST   http://localhost:8080/api/initialize-database

###
# get-transactions-count
GET     http://localhost:8080/api/get-transactions-count

###
#all transactions
GET http://localhost:8080/api/transactions?search=&page=1&perPage=10

###
# statistics
GET  http://localhost:8080/api/statistics/1

###
# bar-chart
GET http://localhost:8080/api/bar-chart/1

###
# pie-chart
GET http://localhost:8080/api/pie-chart/1
###
##product-transactions-statistics-barChart-pieChart

GET http://localhost:8080/api/product-transactions-statistics-barChart-pieChart/1


